### ISSUE TITLE
运行 Main 需要的 jar 有哪些

### ISSUE THREAD

**Issue by googya** [zxh0/jvm.go#13]
/tmp  go/bin/jvmgo -cp /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/jre/lib/rt.jar:.  Main
>> java/util/concurrent/ConcurrentHashMap.<clinit>()V bytecode:21 line:1598
>> java/lang/ClassLoader.<init>(Ljava/lang/Void;Ljava/lang/ClassLoader;)V bytecode:94 line:283
>> java/lang/ClassLoader.<init>(Ljava/lang/ClassLoader;)V bytecode:8 line:318
>> java/security/SecureClassLoader.<init>(Ljava/lang/ClassLoader;)V bytecode:5 line:52
>> java/net/URLClassLoader.<init>([Ljava/net/URL;Ljava/lang/ClassLoader;Ljava/net/URLStreamHandlerFactory;)V bytecode:5 line:207
>> sun/misc/Launcher$ExtClassLoader.<init>([Ljava/io/File;)V bytecode:12 line:165
>> sun/misc/Launcher$ExtClassLoader$1.run()Lsun/misc/Launcher$ExtClassLoader; bytecode:39 line:148
>> sun/misc/Launcher$ExtClassLoader$1.run()Ljava/lang/Object; bytecode:4 line:142
>> java/security/AccessController.doPrivileged(Ljava/security/PrivilegedExceptionAction;)Ljava/lang/Object; bytecode:1 line:-2
>> sun/misc/Launcher$ExtClassLoader.getExtClassLoader()Lsun/misc/Launcher$ExtClassLoader; bytecode:15 line:141
>> sun/misc/Launcher.<init>()V bytecode:7 line:71
>> sun/misc/Launcher.<clinit>()V bytecode:18 line:57
>> java/lang/ClassLoader.initSystemClassLoader()V bytecode:22 line:1489
>> java/lang/ClassLoader.getSystemClassLoader()Ljava/lang/ClassLoader; bytecode:3 line:1475
>> java/lang/Class.getClassLoader0()Ljava/lang/ClassLoader; bytecode:1 line:-2
>> java/lang/Class.getClassLoader()Ljava/lang/ClassLoader; bytecode:4 line:609
>> java/lang/Class.desiredAssertionStatus()Z bytecode:4 line:2975
>> java/lang/Integer.<clinit>()V bytecode:6 line:52
>> java/util/HashMap.roundUpToPowerOf2(I)I bytecode:21 line:303
>> java/util/HashMap.inflateTable(I)V bytecode:4 line:313
>> java/util/HashMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; bytecode:18 line:490
>> sun/reflect/Reflection.<clinit>()V bytecode:31 line:47
>> sun/misc/Unsafe.<clinit>()V bytecode:15 line:49
>> java/util/concurrent/atomic/AtomicInteger.<clinit>()V bytecode:0 line:56
>> java/lang/ThreadLocal.<clinit>()V bytecode:0 line:89
>> java/io/FileInputStream.<clinit>()V bytecode:0 line:63
>> java/lang/System.initializeSystemClass()V bytecode:37 line:1141
>> ~shim.<bootstrap> bytecode:0 line:-1
>> ~shim.<return> bytecode:0 line:-1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7a03e]

goroutine 1 [running]:
github.com/zxh0/jvm.go/jvmgo/jvm/interpreter._catchErr(0x2089f2080)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/interpreter/interpreter.go:68 +0x2b6
github.com/zxh0/jvm.go/jvmgo/jvm/rtda/class.(*ConstantMethodref).GetVirtualMethod(0x208dbed80, 0x0, 0x0)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/rtda/class/cp_methodref.go:104 +0x2e
github.com/zxh0/jvm.go/jvmgo/jvm/instructions.(*invokevirtual).Execute(0x208db9be8, 0x208dc03c0)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/instructions/invokevirtual.go:22 +0x1b6
github.com/zxh0/jvm.go/jvmgo/jvm/interpreter._loop(0x2089f2080)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/interpreter/interpreter.go:45 +0x13d
github.com/zxh0/jvm.go/jvmgo/jvm/interpreter.Loop(0x2089f2080)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/interpreter/interpreter.go:19 +0xbc
github.com/zxh0/jvm.go/jvmgo/jvm.Startup(0x20836ec30)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/jvm.go:19 +0xad
main.main()
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/main.go:14 +0x74

goroutine 5 [semacquire]:
sync.(*Cond).Wait(0x208c6e180)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/cond.go:62 +0x9e
github.com/zxh0/jvm.go/jvmgo/jvm/rtda/class.(*Monitor).Wait(0x208c6e140)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/rtda/class/obj_monitor.go:75 +0xad
github.com/zxh0/jvm.go/jvmgo/native/java/lang.wait(0x208ce6780)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/native/java/lang/Object.go:87 +0xcb
github.com/zxh0/jvm.go/jvmgo/jvm/instructions.(*invoke_native).Execute(0x2c93e0, 0x208ce6780)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/instructions/invoke_native.go:10 +0x6d
github.com/zxh0/jvm.go/jvmgo/jvm/interpreter._loop(0x208c718a0)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/interpreter/interpreter.go:45 +0x13d
github.com/zxh0/jvm.go/jvmgo/jvm/interpreter.Loop(0x208c718a0)
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/jvm/interpreter/interpreter.go:19 +0xbc
created by github.com/zxh0/jvm.go/jvmgo/native/java/lang.start0
	/tmp/go/src/github.com/zxh0/jvm.go/jvmgo/native/java/lang/Thread.go:102 +0x1a4

**Comment by beyondblog** [comment]
jdk 没选对 目前是 支持1.8 去http://www.azulsystems.com/products/zulu/downloads#mac下载  基于openJDK 版本的  然后把 里面的 jre 目录copy 出来 ,参考 README 上的流程就能运行起来 : )

**Comment by googya** [comment]
是不是非要 zulu 的 jdk， oracle 的不行呢？

```shell
➜  go  javac -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
javac 1.8.0_05

```shell
➜  go  echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home
```

**Comment by beyondblog** [comment]
oracle 的可能不兼容,涉及到版权问题,采用了基于OpenJDK的zulujdk,你从README上面的链接哪儿下载一个 解压之后把里面的jre文件夹考出来 放到  jvmgo的运行路径下即可

:  )

**Comment by zxh0** [comment]
Oracle也可以，但是版本最好是1.8.0_31。
