### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by andrewchambers** [zxh0/jvm.go#39]
Can I ask if you made that logo yourself? It is really cool and wondered if you had original files, or svg files? I am working on a C compiler in Go* and would love a similar logo, but lack any art skills.

 *https://github.com/andrewchambers/cc

**Comment by zxh0** [comment]
Hi, this logo was made by my friend, a boy artist. I am happy that you like it. I only have the psd file. I have uploaded it into repository. Feel free to use it :)

**Comment by andrewchambers** [comment]
Thanks!

**Comment by beyondblog** [comment]
cool~  
:)
