### ISSUE TITLE
Do not change users' GOPATH

### ISSUE THREAD

**Issue by monnand** [zxh0/jvm.go#4]
It is considered as a bad practice to ask users to change their GOPATH to build some library/program. Because users could not install the program through ``go get``. More details could be found [here](http://blog.golang.org/organizing-go-code). To quote:

> Sometimes people set GOPATH to the root of their source repository and put their packages in directories relative to the repository root, such as "src/my/package". On one hand, this keeps the import paths short ("my/package" instead of "github.com/me/project/my/package"), but on the other it breaks go get and forces users to re-set their GOPATH to use the package. **Don't do this.**

To make it more idiomatic, I would suggest you to move every thing in ``src/`` to the root directory and change the import paths accordingly.

**Comment by zxh0** [comment]
work in progress...

**Comment by dchapes** [comment]
Seconded. It's the first thing I noticed from the readme and it makes it obvious you didn't read/understand [How to Write Go Code](https://golang.org/doc/code.html); so why should anyone look any further at any Go code you write?

**Comment by zxh0** [comment]
Yes, I didn't understand How to Write Go Code clearly :( 
I have fixed this issue.
