### ISSUE TITLE
Error running jvmgo

### ISSUE THREAD

**Issue by tinycedar** [zxh0/jvm.go#40]
![error](https://cloud.githubusercontent.com/assets/8019222/7311568/a0906668-ea70-11e4-84bb-45054a5f5fae.JPG)

**Comment by beyondblog** [comment]
not compatible with windows systems,we will improve

**Comment by tinycedar** [comment]
Well, how about Ubuntu ?

**Comment by beyondblog** [comment]
support ubuntu ： ）

发自我的 iPhone

**Comment by tinycedar** [comment]
Still error running in Ubuntu 14.10 with OpenJDK:

![screenshot from 2015-04-25 00 23 19](https://cloud.githubusercontent.com/assets/8019222/7323461/50009184-eae1-11e4-88d4-11a66bb57c23.png)

**Comment by zxh0** [comment]
Hi, I guess your problem is not OS, it's the way you run jvm.go.
You need to follow the readme.md to run it.

**Comment by tinycedar** [comment]
I put the jvmgo.exe into Oracle JDK folder, but output says cannot find the native method:
![screenshot](https://cloud.githubusercontent.com/assets/8019222/7331339/b8e9b1a6-eb3d-11e4-97a7-e0d6bc34ab29.JPG)

**Comment by tinycedar** [comment]
I've read some code and ran the test class successfully in Ubuntu, but Windows seems not compatible. Really appreciate your help.

**Comment by zxh0** [comment]
You are welcome :)
