### ISSUE TITLE
Expose Instructions

### ISSUE THREAD

**Issue by cretz** [zxh0/jvm.go#44]
Myself (and probably many others) would like to use the classloader and instruction decoder to do analysis on class files. Any plans to expose the different instruction structs or at least the name?

**Comment by zxh0** [comment]
Thanks for you advice but I am afraid I have no time to do this. This project was coded a half year ago when I quit my job and get some free time at home. After that  the project is almost stopped.

**Comment by cretz** [comment]
No worries, thanks for the update. I forked it and exposed some stuff myself for classfile parsing. Thanks again for the code.
