### ISSUE TITLE
This Exists

### ISSUE THREAD

**Issue by konalisp** [zxh0/jvm.go#5]
Bug: This exists
How to reproduce: Go to https://github.com/zxh0/jvm.go
Expected Result: No JVM written in Go using Sublime Text
Result: JVM written in Go using Sublime Text
How to fix: Delete repository, rethink life choices

**Comment by joshumax** [comment]
You're issue makes absolutely no sense, but you already knew that...

![iw3el](https://cloud.githubusercontent.com/assets/1807142/6659043/f0b29460-cb38-11e4-872d-0a8c65331a0f.jpg)

**Comment by konalisp** [comment]
Your*

**Comment by joshumax** [comment]
Clearly your attempts to both correct a minor spelling mistake made by me with the implicit intention to illicit personal aggravation, and then create what I can only assume to be a separate spam GitHub account to send another bogus pull request removing all files in the repository helps make you a better human being. I will say this one last time and then leave it to the project maintainer to resolve the issue: please stop spamming the issues page of this repository.

**Comment by konalisp** [comment]
Ok, kid

**Comment by andrewchambers** [comment]
@konalisp You should probably rethink your own life choices. You are bitter and hateful, I hope you have some redeeming qualities, because I can't see any. Perhaps IF you create something notable, others will be able to give you the same treatment you dish out.

**Comment by konalisp** [comment]
@andrewchambers Ok, kid

**Comment by zxh0** [comment]
It's Not a Bug, It's a Feature : )
