### ISSUE TITLE
你那本数第二版什么时候出呀，记得把多线程和垃圾回收实现以下。

### ISSUE THREAD

**Issue by 1228857713** [zxh0/jvm.go#65]
你那本数第二版什么时候出呀，记得把多线程和垃圾回收实现以下。好了记得提醒我去买

**Comment by zxh0** [comment]
还在写。。。。。。心急的话可以关注一下我的下一本书《WebAssembly原理与核心技术》，估计快出版了😅

**Comment by 1228857713** [comment]
出了第一时间告诉我，我去买一本
